// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceTruckers.Infrastructure.Persistence.EfCore;

#nullable disable

namespace SpaceTruckers.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(SpaceTruckersDbContext))]
    [Migration("20260214034539_TripVersionTrigger")]
    partial class TripVersionTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceTruckers.Domain.Resources.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("SpaceTruckers.Domain.Resources.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CargoCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("SpaceTruckers.Domain.Routes.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("SpaceTruckers.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CargoRequirement")
                        .HasColumnType("integer");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastReachedCheckpointIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint");

                    b.Property<string[]>("_startTripRequestIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("start_trip_request_ids");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("SpaceTruckers.Infrastructure.Persistence.EfCore.ResourceBooking", b =>
                {
                    b.Property<string>("ResourceType")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("ResourceType", "ResourceId");

                    b.HasIndex("TripId");

                    b.ToTable("resource_bookings", (string)null);
                });

            modelBuilder.Entity("SpaceTruckers.Infrastructure.Persistence.EfCore.TripEvent", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("TripId", "Sequence");

                    b.HasIndex("TripId");

                    b.ToTable("trip_events", (string)null);
                });

            modelBuilder.Entity("SpaceTruckers.Domain.Routes.Route", b =>
                {
                    b.OwnsMany("SpaceTruckers.Domain.Routes.RouteCheckpoint", "_checkpoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("RouteId", "Sequence")
                                .IsUnique();

                            b1.ToTable("route_checkpoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("_checkpoints");
                });

            modelBuilder.Entity("SpaceTruckers.Domain.Trips.Trip", b =>
                {
                    b.OwnsMany("SpaceTruckers.Domain.Trips.TripCheckpoint", "_checkpoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TripId", "Sequence")
                                .IsUnique();

                            b1.ToTable("trip_checkpoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("_checkpoints");
                });

            modelBuilder.Entity("SpaceTruckers.Infrastructure.Persistence.EfCore.TripEvent", b =>
                {
                    b.HasOne("SpaceTruckers.Domain.Trips.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
